version: "3"

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: myprojectuser
  #     POSTGRES_DB: myproject22
  #     POSTGRES_PASS: password
  #   volumes:
  #     - pgdata:/var/lib/posgresql/data
  app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./blog:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # depends_on:
    #   - db  

# volumes:
#   pgdata: